
services:
  app:
    build: .
    ports:
      - "5000"
    environment:
      - PORT=5000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - REDIS_HOST=cache
      - REDIS_PORT=6379

  cache:
    image: redis:7-alpine
